# Generated by Django 6.0.7 on 2026-07-27 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=5)),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('profit_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
