# Generated by Django 6.0.7 on 2026-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_salelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garments/'),
        ),
    ]
