# Generated by Django 6.0.7 on 2026-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='breakdown',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
