# Generated by Django 6.0.2 on 2026-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
