# Generated by Django 6.0.2 on 2026-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_preorder_down_payment_preorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='batch_name',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
