# Generated by Django 6.0.2 on 2026-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_garment_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='category',
            field=models.CharField(blank=True, default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='batch_name',
            field=models.CharField(blank=True, default='Uncategorized', max_length=255, null=True),
        ),
    ]
