# Generated by Django 6.0.2 on 2026-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_garment_category_garment_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='salelog',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
