# Generated by Django 6.0.2 on 2026-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_preorder_status_salelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Received', 'Received')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='salelog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Received', 'Received')], default='Pending', max_length=50),
        ),
    ]
