# Generated by Django 6.0.2 on 2026-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_preorder_address_alter_preorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
