# Generated by Django 6.0.2 on 2026-08-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_preorder_contact_number_preorder_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
