# Generated by Django 6.0.2 on 2026-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_preorder_contact_number_preorder_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='garment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salelog',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salelog',
            name='garment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
