# Generated by Django 6.0.2 on 2026-09-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_preorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salelog',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
