# Generated by Django 6.0.7 on 2026-10-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_backfill_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelog',
            name='garment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
