# Generated by Django 6.0.7 on 2026-10-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_salelog_garment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelog',
            name='amount_sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
